import type {
  AIQuestionSimulation,
  BuyerQuestionCategory,
  BuyerQuestionSimulationReport,
  FindingCategory,
  PageCandidateKey,
  PolicyContentPageSnapshot,
  PolicyContentReport,
  PolicyCoverageKey,
  PublicDiscoveryReport,
  QuestionResultStatus,
  QuestionSourceReference,
  ScanFinding,
  StoreTruthProductSnapshot,
} from "./types";

const QUESTION_STATUSES: QuestionResultStatus[] = [
  "answered",
  "partially_answered",
  "unanswered",
  "unclear",
  "contradiction_risk",
];

const QUESTION_CATEGORIES: BuyerQuestionCategory[] = [
  "product_recommendation",
  "product_comparison",
  "shipping",
  "returns_refunds",
  "warranty_support",
  "sizing_options",
  "compatibility_specs",
  "materials_use_case",
  "contact_help_faq",
];

const STATUS_SCORES: Record<QuestionResultStatus, number> = {
  answered: 100,
  partially_answered: 60,
  unanswered: 0,
  unclear: 35,
  contradiction_risk: 20,
};

export function createBuyerQuestionSimulationReport({
  findings,
  generatedAt,
  policyContent,
  products,
  publicDiscovery,
}: {
  findings: ScanFinding[];
  generatedAt: string;
  policyContent: PolicyContentReport;
  products: StoreTruthProductSnapshot[];
  publicDiscovery: PublicDiscoveryReport;
}): BuyerQuestionSimulationReport {
  const questions = [
    createProductRecommendationQuestion(products, findings),
    createProductComparisonQuestion(products, findings),
    createPolicyQuestion({
      category: "shipping",
      findingKey: "shipping",
      findings,
      policyContent,
      question: "Can a buyer understand shipping or delivery expectations before purchase?",
      questionId: "question-shipping-expectations",
    }),
    createPolicyQuestion({
      category: "returns_refunds",
      findingKey: "returns",
      findings,
      policyContent,
      question: "Can a buyer understand return, refund, or exchange options before purchase?",
      questionId: "question-return-refund-options",
    }),
    createWarrantySupportQuestion(products, policyContent, findings),
    createSizingOptionsQuestion(products, findings),
    createCompatibilitySpecsQuestion(products, findings),
    createMaterialsUseCaseQuestion(products, findings),
    createContactHelpFaqQuestion(policyContent, findings),
    createPublicDiscoveryQuestion(publicDiscovery, findings),
  ];
  const questionFindings = createQuestionFindings(questions);

  return {
    id: `question-simulation-${generatedAt.replace(/[:.]/g, "-")}`,
    generatedAt,
    method: "local_template_rules",
    readOnly: true,
    score: calculateQuestionCoverageScore(questions),
    summary: createQuestionSummary(questions),
    questions,
    findings: questionFindings,
    notes: [
      "No AI provider is called. Questions and classifications are generated by deterministic local templates.",
      "Classifications are readiness signals only; they are not claims about AI rankings, traffic, or sales.",
      "Questions use the bounded product scan, public discovery checks, and policy/content scan already present in this local report.",
    ],
  };
}

function createProductRecommendationQuestion(
  products: StoreTruthProductSnapshot[],
  findings: ScanFinding[],
): AIQuestionSimulation {
  if (products.length === 0) {
    return createQuestion({
      category: "product_recommendation",
      id: "question-product-recommendation",
      question:
        "Can a buyer get a source-backed product recommendation from the scanned catalog?",
      resultStatus: "unanswered",
      riskFlags: ["no_products_returned"],
      sourceReferences: findingReferences(
        findings,
        (finding) => finding.id === "finding-no-products-returned",
      ),
      sourceSummary: "No products were returned by the bounded product scan.",
    });
  }

  const weakProducts = products.filter(
    (product) =>
      product.description.textLength < 120 ||
      countStructuredProductSignals(product) < 2,
  );
  const resultStatus =
    weakProducts.length === 0 ? "answered" : "partially_answered";

  return createQuestion({
    category: "product_recommendation",
    id: "question-product-recommendation",
    question:
      "Can a buyer get a source-backed product recommendation from the scanned catalog?",
    resultStatus,
    riskFlags:
      weakProducts.length > 0 ? ["thin_descriptions_or_sparse_attributes"] : [],
    sourceReferences: [
      ...productReferences(products),
      ...findingReferences(
        findings,
        (finding) =>
          finding.category === "product_readiness" &&
          finding.resourceType === "product",
      ),
    ],
    sourceSummary:
      weakProducts.length === 0
        ? "Scanned products include description text and structured product signals for a basic recommendation check."
        : `${weakProducts.length} scanned product(s) have thin descriptions or sparse structured attributes.`,
  });
}

function createProductComparisonQuestion(
  products: StoreTruthProductSnapshot[],
  findings: ScanFinding[],
): AIQuestionSimulation {
  if (products.length < 2) {
    return createQuestion({
      category: "product_comparison",
      id: "question-product-comparison",
      question:
        "Can a buyer compare two products using source-backed differences?",
      resultStatus: "unanswered",
      riskFlags: ["fewer_than_two_products"],
      sourceReferences: productReferences(products),
      sourceSummary:
        "The bounded product sample has fewer than two products to compare.",
    });
  }

  const comparableProducts = products.filter(
    (product) =>
      product.description.textLength >= 120 &&
      (product.productType ||
        product.tags.length > 0 ||
        product.options.some((option) => option.valueCount > 0)),
  );
  const resultStatus =
    comparableProducts.length >= 2 ? "answered" : "partially_answered";

  return createQuestion({
    category: "product_comparison",
    id: "question-product-comparison",
    question: "Can a buyer compare two products using source-backed differences?",
    resultStatus,
    riskFlags:
      comparableProducts.length >= 2
        ? []
        : ["missing_comparison_attributes"],
    sourceReferences: [
      ...productReferences(products),
      ...findingReferences(
        findings,
        (finding) =>
          finding.id.includes("structured-attributes") ||
          finding.id.includes("thin-description"),
      ),
    ],
    sourceSummary:
      comparableProducts.length >= 2
        ? "At least two scanned products have enough descriptive or structured fields for a basic comparison."
        : "The scan returned multiple products, but comparison fields are thin or inconsistent.",
  });
}

function createPolicyQuestion({
  category,
  findingKey,
  findings,
  policyContent,
  question,
  questionId,
}: {
  category: "shipping" | "returns_refunds";
  findingKey: PolicyCoverageKey;
  findings: ScanFinding[];
  policyContent: PolicyContentReport;
  question: string;
  questionId: string;
}): AIQuestionSimulation {
  const signal = policyContent.coverage.policies.find(
    (candidate) => candidate.key === findingKey,
  );
  const matchedPages = matchedPagesForGids(
    policyContent.pages,
    signal?.matchedPageGids ?? [],
  );
  const resultStatus = classifyPolicyPages(matchedPages, signal?.present ?? false);
  const missingFindingId = `finding-missing-${findingKey}-policy`;

  return createQuestion({
    category,
    id: questionId,
    question,
    resultStatus,
    riskFlags: policyRiskFlags(matchedPages, signal?.present ?? false),
    sourceReferences: [
      ...pageReferences(matchedPages),
      ...findingReferences(
        findings,
        (finding) => finding.id === missingFindingId,
      ),
    ],
    sourceSummary: policySourceSummary(matchedPages, signal?.label ?? findingKey),
  });
}

function createWarrantySupportQuestion(
  products: StoreTruthProductSnapshot[],
  policyContent: PolicyContentReport,
  findings: ScanFinding[],
): AIQuestionSimulation {
  const supportPages = pagesForCandidateKeys(policyContent, ["help", "faq"]);
  const contactPages = pagesForCandidateKeys(policyContent, ["contact"]);
  const productWarrantySignals = products.filter((product) =>
    /\b(warranty|guarantee|support|care|repair)\b/i.test(productText(product)),
  );
  const resultStatus =
    supportPages.some((page) => page.bodyTextLength >= 120) ||
    productWarrantySignals.length > 0
      ? "answered"
      : supportPages.length > 0 || contactPages.length > 0
        ? "partially_answered"
        : "unanswered";

  return createQuestion({
    category: "warranty_support",
    id: "question-warranty-support",
    question:
      "Can a buyer understand warranty, care, or support options for a product?",
    resultStatus,
    riskFlags:
      resultStatus === "answered"
        ? []
        : ["missing_or_thin_warranty_support_sources"],
    sourceReferences: [
      ...pageReferences([...supportPages, ...contactPages]),
      ...productReferences(productWarrantySignals),
      ...findingReferences(
        findings,
        (finding) =>
          finding.id === "finding-missing-help-page" ||
          finding.id === "finding-missing-faq-page" ||
          finding.id.includes("thin-content"),
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "The scan found support source text in product or help/FAQ content."
        : "The scan did not find enough warranty, care, or support source text.",
  });
}

function createSizingOptionsQuestion(
  products: StoreTruthProductSnapshot[],
  findings: ScanFinding[],
): AIQuestionSimulation {
  const productsWithOptions = products.filter((product) =>
    product.options.some((option) => option.valueCount > 0),
  );
  const productsWithNamedOptions = productsWithOptions.filter((product) =>
    product.options.some((option) =>
      /\b(size|width|length|height|color|style|fit|option)\b/i.test(
        option.name,
      ),
    ),
  );
  const resultStatus =
    products.length === 0
      ? "unanswered"
      : productsWithNamedOptions.length > 0
        ? "answered"
        : productsWithOptions.length > 0
          ? "partially_answered"
          : "unclear";

  return createQuestion({
    category: "sizing_options",
    id: "question-sizing-options",
    question: "Can a buyer understand size, option, or variant choices?",
    resultStatus,
    riskFlags:
      resultStatus === "answered" ? [] : ["missing_or_generic_option_data"],
    sourceReferences: [
      ...productReferences(productsWithOptions.length > 0 ? productsWithOptions : products),
      ...findingReferences(
        findings,
        (finding) => finding.id.includes("structured-attributes"),
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "At least one scanned product has named option values that can support option-related questions."
        : "Option or variant data is missing, generic, or too sparse for a confident sizing/options answer.",
  });
}

function createCompatibilitySpecsQuestion(
  products: StoreTruthProductSnapshot[],
  findings: ScanFinding[],
): AIQuestionSimulation {
  const productsWithSpecSignals = products.filter((product) =>
    /\b(compatible|compatibility|fits|fit|dimensions|dimension|weight|capacity|spec|specs|model)\b/i.test(
      productText(product),
    ),
  );
  const productsWithStructuredContext = products.filter(
    (product) => countStructuredProductSignals(product) >= 2,
  );
  const resultStatus =
    products.length === 0
      ? "unanswered"
      : productsWithSpecSignals.length > 0
        ? "answered"
        : productsWithStructuredContext.length > 0
          ? "partially_answered"
          : "unclear";

  return createQuestion({
    category: "compatibility_specs",
    id: "question-compatibility-specs",
    question:
      "Can a buyer answer compatibility or specification questions from store data?",
    resultStatus,
    riskFlags:
      resultStatus === "answered" ? [] : ["missing_specs_or_compatibility_terms"],
    sourceReferences: [
      ...productReferences(
        productsWithSpecSignals.length > 0
          ? productsWithSpecSignals
          : productsWithStructuredContext,
      ),
      ...findingReferences(
        findings,
        (finding) =>
          finding.id.includes("structured-attributes") ||
          finding.id.includes("thin-description"),
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "Product summaries or structured fields contain compatibility/specification signals."
        : "The bounded product data has limited explicit compatibility or specification signals.",
  });
}

function createMaterialsUseCaseQuestion(
  products: StoreTruthProductSnapshot[],
  findings: ScanFinding[],
): AIQuestionSimulation {
  const productsWithMaterialSignals = products.filter((product) =>
    /\b(cotton|canvas|leather|wood|walnut|metal|steel|plastic|glass|material|materials|made|use|uses|indoor|outdoor)\b/i.test(
      productText(product),
    ),
  );
  const descriptiveProducts = products.filter(
    (product) => product.description.textLength >= 120,
  );
  const resultStatus =
    products.length === 0
      ? "unanswered"
      : productsWithMaterialSignals.length > 0 && descriptiveProducts.length > 0
        ? "answered"
        : descriptiveProducts.length > 0
          ? "partially_answered"
          : "unanswered";

  return createQuestion({
    category: "materials_use_case",
    id: "question-materials-use-case",
    question:
      "Can a buyer understand product materials or likely use cases from source data?",
    resultStatus,
    riskFlags:
      resultStatus === "answered" ? [] : ["missing_materials_or_use_case_detail"],
    sourceReferences: [
      ...productReferences(
        productsWithMaterialSignals.length > 0
          ? productsWithMaterialSignals
          : descriptiveProducts,
      ),
      ...findingReferences(
        findings,
        (finding) => finding.id.includes("thin-description"),
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "Product text includes material or use-case signals."
        : "Product text is too thin or lacks clear material/use-case signals.",
  });
}

function createContactHelpFaqQuestion(
  policyContent: PolicyContentReport,
  findings: ScanFinding[],
): AIQuestionSimulation {
  const pages = pagesForCandidateKeys(policyContent, ["contact", "help", "faq"]);
  const substantialPages = pages.filter((page) => page.bodyTextLength >= 120);
  const resultStatus =
    substantialPages.length > 0
      ? "answered"
      : pages.length > 0
        ? "partially_answered"
        : "unanswered";

  return createQuestion({
    category: "contact_help_faq",
    id: "question-contact-help-faq",
    question:
      "Can a buyer find contact, help, or FAQ sources for store-level questions?",
    resultStatus,
    riskFlags:
      resultStatus === "answered" ? [] : ["missing_or_thin_help_sources"],
    sourceReferences: [
      ...pageReferences(pages),
      ...findingReferences(
        findings,
        (finding) =>
          finding.id === "finding-missing-contact-page" ||
          finding.id === "finding-missing-help-page" ||
          finding.id === "finding-missing-faq-page" ||
          finding.id.includes("thin-content"),
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "The bounded page scan found contact/help/FAQ source text."
        : "Contact/help/FAQ sources are missing or too thin for confident answers.",
  });
}

function createPublicDiscoveryQuestion(
  publicDiscovery: PublicDiscoveryReport,
  findings: ScanFinding[],
): AIQuestionSimulation {
  const requiredPublicFiles = publicDiscovery.results.filter(
    (result) => result.path === "/robots.txt" || result.path === "/sitemap.xml",
  );
  const optionalAgentFiles = publicDiscovery.results.filter(
    (result) =>
      result.path === "/agents.md" ||
      result.path === "/llms.txt" ||
      result.path === "/llms-full.txt",
  );
  const reachableRequired = requiredPublicFiles.filter(
    (result) => result.status === "reachable",
  );
  const reachableAgentFiles = optionalAgentFiles.filter(
    (result) => result.status === "reachable",
  );
  const blockedOrErrored = publicDiscovery.results.filter((result) =>
    ["blocked", "timeout", "error"].includes(result.status),
  );
  const resultStatus =
    blockedOrErrored.length > 0
      ? "unclear"
      : reachableAgentFiles.length > 0
        ? "answered"
        : reachableRequired.length > 0
          ? "partially_answered"
          : "unanswered";

  return createQuestion({
    category: "contact_help_faq",
    id: "question-public-discovery",
    question:
      "Can an external agent find declared public discovery surfaces before answering store questions?",
    resultStatus,
    riskFlags:
      resultStatus === "answered" ? [] : ["missing_or_limited_public_discovery"],
    sourceReferences: [
      ...publicDiscovery.results.map((result) => ({
        type: "discovery_url" as const,
        discoveryPath: result.path,
        label: `${result.path}: ${result.status}`,
      })),
      ...findingReferences(
        findings,
        (finding) => finding.category === "agent_discovery",
      ),
    ],
    sourceSummary:
      resultStatus === "answered"
        ? "At least one optional agent-facing discovery file is reachable."
        : "Public discovery is limited, missing, blocked, or only partially available.",
  });
}

function createQuestion({
  category,
  id,
  question,
  resultStatus,
  riskFlags,
  sourceReferences,
  sourceSummary,
}: AIQuestionSimulation): AIQuestionSimulation {
  return {
    id,
    question,
    category,
    resultStatus,
    sourceSummary,
    sourceReferences: sourceReferences.slice(0, 8),
    riskFlags,
  };
}

function classifyPolicyPages(
  pages: PolicyContentPageSnapshot[],
  present: boolean,
): QuestionResultStatus {
  if (!present || pages.length === 0) {
    return "unanswered";
  }

  if (hasContradictionRisk(pages)) {
    return "contradiction_risk";
  }

  if (pages.some((page) => page.bodyTextLength >= 120)) {
    return "answered";
  }

  return "partially_answered";
}

function policyRiskFlags(
  pages: PolicyContentPageSnapshot[],
  present: boolean,
): string[] {
  if (!present || pages.length === 0) {
    return ["missing_policy_source"];
  }

  if (hasContradictionRisk(pages)) {
    return ["multiple_distinct_policy_sources"];
  }

  if (pages.every((page) => page.bodyTextLength < 120)) {
    return ["thin_policy_source"];
  }

  return [];
}

function policySourceSummary(
  pages: PolicyContentPageSnapshot[],
  label: string,
): string {
  if (pages.length === 0) {
    return `No page title or handle matched ${label}.`;
  }

  if (hasContradictionRisk(pages)) {
    return `${pages.length} pages matched ${label} with different body hashes, which should be reviewed for source consistency.`;
  }

  if (pages.some((page) => page.bodyTextLength >= 120)) {
    return `${pages.length} page candidate(s) matched ${label}; at least one has substantial source text.`;
  }

  return `${pages.length} page candidate(s) matched ${label}, but the body text is thin.`;
}

function hasContradictionRisk(pages: PolicyContentPageSnapshot[]): boolean {
  const distinctNonEmptyHashes = new Set(
    pages
      .filter((page) => page.bodyTextLength >= 20)
      .map((page) => page.bodySha256),
  );

  return distinctNonEmptyHashes.size > 1;
}

function pagesForCandidateKeys(
  policyContent: PolicyContentReport,
  keys: PageCandidateKey[],
): PolicyContentPageSnapshot[] {
  const keySet = new Set(keys);
  const gids = new Set(
    policyContent.coverage.pageCandidates
      .filter((candidate) => keySet.has(candidate.key))
      .flatMap((candidate) => candidate.matchedPageGids),
  );

  return matchedPagesForGids(policyContent.pages, [...gids]);
}

function matchedPagesForGids(
  pages: PolicyContentPageSnapshot[],
  pageGids: string[],
): PolicyContentPageSnapshot[] {
  const gidSet = new Set(pageGids);

  return pages.filter((page) => gidSet.has(page.pageGid));
}

function productReferences(
  products: StoreTruthProductSnapshot[],
): QuestionSourceReference[] {
  return products.slice(0, 3).map((product) => ({
    type: "product",
    productGid: product.productGid,
    productTitle: product.title,
    productHandle: product.handle,
    label: `Product: ${product.title} (${product.handle})`,
  }));
}

function pageReferences(
  pages: PolicyContentPageSnapshot[],
): QuestionSourceReference[] {
  return pages.slice(0, 4).map((page) => ({
    type: "policy_page",
    pageGid: page.pageGid,
    pageTitle: page.title,
    pageHandle: page.handle,
    label: `Page: ${page.title} (${page.handle})`,
  }));
}

function findingReferences(
  findings: ScanFinding[],
  predicate: (finding: ScanFinding) => boolean,
  limit = 4,
): QuestionSourceReference[] {
  return findings
    .filter(predicate)
    .slice(0, limit)
    .map((finding) => ({
      type: "finding",
      findingId: finding.id,
      findingCategory: finding.category as FindingCategory,
      label: `Finding: ${finding.title}`,
    }));
}

function createQuestionSummary(
  questions: AIQuestionSimulation[],
): BuyerQuestionSimulationReport["summary"] {
  const byStatus = Object.fromEntries(
    QUESTION_STATUSES.map((status) => [status, 0]),
  ) as Record<QuestionResultStatus, number>;
  const byCategory = Object.fromEntries(
    QUESTION_CATEGORIES.map((category) => [category, 0]),
  ) as Record<BuyerQuestionCategory, number>;
  const sourceSignalsUsed = new Set<string>();

  for (const question of questions) {
    byStatus[question.resultStatus] += 1;
    byCategory[question.category] += 1;

    for (const reference of question.sourceReferences) {
      sourceSignalsUsed.add(reference.type);
    }
  }

  return {
    totalQuestions: questions.length,
    byStatus,
    byCategory,
    sourceSignalsUsed: [...sourceSignalsUsed].sort(),
  };
}

function calculateQuestionCoverageScore(
  questions: AIQuestionSimulation[],
): number {
  if (questions.length === 0) {
    return 0;
  }

  return Math.round(
    questions.reduce((sum, question) => {
      return sum + STATUS_SCORES[question.resultStatus];
    }, 0) / questions.length,
  );
}

function createQuestionFindings(
  questions: AIQuestionSimulation[],
): ScanFinding[] {
  return questions
    .filter((question) => question.resultStatus !== "answered")
    .map((question) => ({
      id: `finding-${question.id}`,
      severity: questionFindingSeverity(question.resultStatus),
      category: "ai_question_coverage",
      resourceType: resourceTypeForQuestion(question),
      ...(resourceGidForQuestion(question)
        ? { resourceGid: resourceGidForQuestion(question) }
        : {}),
      title: `Buyer question is ${question.resultStatus.replace(/_/g, " ")}`,
      description: question.question,
      evidence: {
        questionId: question.id,
        questionCategory: question.category,
        resultStatus: question.resultStatus,
        sourceReferenceCount: question.sourceReferences.length,
        riskFlags: question.riskFlags,
      },
      recommendation:
        "Review the referenced source gaps and draft merchant-approved source content before relying on this answer path.",
      status: "open",
    }));
}

function questionFindingSeverity(
  status: QuestionResultStatus,
): "low" | "medium" | "high" {
  if (status === "unanswered" || status === "contradiction_risk") {
    return "medium";
  }

  return "low";
}

function resourceTypeForQuestion(
  question: AIQuestionSimulation,
): ScanFinding["resourceType"] {
  const firstReference = question.sourceReferences[0];

  if (firstReference?.type === "product") {
    return "product";
  }

  if (firstReference?.type === "policy_page") {
    return "policy";
  }

  if (firstReference?.type === "discovery_url") {
    return "discovery_url";
  }

  return "store";
}

function resourceGidForQuestion(
  question: AIQuestionSimulation,
): string | undefined {
  const firstReference = question.sourceReferences[0];

  return firstReference?.productGid ?? firstReference?.pageGid;
}

function countStructuredProductSignals(product: StoreTruthProductSnapshot): number {
  return [
    Boolean(product.productType),
    Boolean(product.vendor),
    product.tags.length > 0,
    product.options.some((option) => option.valueCount > 0),
  ].filter(Boolean).length;
}

function productText(product: StoreTruthProductSnapshot): string {
  return [
    product.title,
    product.handle,
    product.productType,
    product.vendor,
    product.tags.join(" "),
    product.description.textSummary,
    product.options.map((option) => `${option.name} ${option.sampleValues.join(" ")}`).join(" "),
    product.images.sampleAltTexts.join(" "),
  ].join(" ");
}
